### ISSUE TITLE
Build is never clean

### ISSUE THREAD

**Issue by kirkeby** [im-0/log4rs-syslog#16]
Hi,

Because of `build.rs` builds of `log4rs-syslog` are never "done" (`cargo build` will always build log4rs-syslog and any crate that depends on it), when you have a workspace with a bunch of crates depending on log4rs-syslog that causes a lot of build-churn.

I'm guessing skeptic writes files to `tests/` marking the source-tree newer than the build it produces.

Is it possible to use skeptic without it causing build-churn like this?

/s

**Comment by im-0** [comment]
It seems that currently it is not possible to use skeptic without triggering rebuild every time, see budziq/rust-skeptic#60.

However, thanks to code examples in that issue, I was able to replace skeptic with direct run of "rustdoc --test README.md".

Fixed version 3.0.1 was just released on crates.io, so please test.

**Comment by kirkeby** [comment]
It works beautifully, thanks a lot :)
